name: Open Referral API
url: http://developer.open.referral.adopta.agency/

author:
  name: 'Open Referral'
  email: 'info@openreferral.org'
markdown: kramdown

permalink: /:categories/:year/:month/:day/:title/
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

get_color: 009900;
post_color: 0000ff;
put_color: FF0080;
delete_color: FF9900;

github_org: human-services
github_repo: portal

# Social media for header
twitter: openreferral
github: openreferral


# URL to the issues page for this
support_title: Support
support_description: If you need any help, have questions, or would like to get involved, please use the following links.
support_email: info@openreferral.org
support_twitter: openreferral

# Login area
login:
signup:

# blog stuff
permalink: /:categories/:year/:month/:day/:title/
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", ".DS_Store"]

paginate: 150
paginate_path: "/blog/page:num"

status_key: ASzjKOjFKPYC0D-RBGPWtw
status_id: 1572918

# Footer
footer_title: Open Referral Developer Portal
footer_link: http://openreferral.org
footer_image_source: http://openreferral.org
footer_image_width: 60

gems: [jekyll-paginate]